CREATE DATABASE IF NOT EXISTS pokedexdb;

USE pokedexdb;

BEGIN;

/*Pokemon*/
INSERT INTO pokemon(name) values('Bulbasaur');
INSERT INTO pokemon(name) values('Ivysaur');
INSERT INTO pokemon(name) values('Venusaur');
INSERT INTO pokemon(name) values('Charmander');
INSERT INTO pokemon(name) values('Charmeleon');
INSERT INTO pokemon(name) values('Charizard');
INSERT INTO pokemon(name) values('Squirtle');
INSERT INTO pokemon(name) values('Wartortle');
INSERT INTO pokemon(name) values('Blastoise');
INSERT INTO pokemon(name) values('Caterpie');
INSERT INTO pokemon(name) values('Metapod');
INSERT INTO pokemon(name) values('Butterfree');
INSERT INTO pokemon(name) values('Weedle');
INSERT INTO pokemon(name) values('Kakuna');
INSERT INTO pokemon(name) values('Beedrill');
INSERT INTO pokemon(name) values('Pidgey');
INSERT INTO pokemon(name) values('Pidgeotto');
INSERT INTO pokemon(name) values('Pidgeot');
INSERT INTO pokemon(name) values('Rattata');
INSERT INTO pokemon(name) values('Raticate');
INSERT INTO pokemon(name) values('Spearow');
INSERT INTO pokemon(name) values('Fearow');
INSERT INTO pokemon(name) values('Ekans');
INSERT INTO pokemon(name) values('Arbok');
INSERT INTO pokemon(name) values('Pikachu');
INSERT INTO pokemon(name) values('Raichu');
INSERT INTO pokemon(name) values('Sandshrew');
INSERT INTO pokemon(name) values('Sandslash');
INSERT INTO pokemon(name) values('NidoranH');
INSERT INTO pokemon(name) values('Nidorina');
INSERT INTO pokemon(name) values('Nidoqueen');
INSERT INTO pokemon(name) values('NidoranM');
INSERT INTO pokemon(name) values('Nidorino');
INSERT INTO pokemon(name) values('Nidoking');
INSERT INTO pokemon(name) values('Clefairy');
INSERT INTO pokemon(name) values('Clefable');
INSERT INTO pokemon(name) values('Vulpix');
INSERT INTO pokemon(name) values('Ninetales');
INSERT INTO pokemon(name) values('Jigglypuff');
INSERT INTO pokemon(name) values('Wigglytuff');
INSERT INTO pokemon(name) values('Zubat');
INSERT INTO pokemon(name) values('Golbat');
INSERT INTO pokemon(name) values('Oddish');
INSERT INTO pokemon(name) values('Gloom');
INSERT INTO pokemon(name) values('Vileplume');
INSERT INTO pokemon(name) values('Paras');
INSERT INTO pokemon(name) values('Parasect');
INSERT INTO pokemon(name) values('Venonat');
INSERT INTO pokemon(name) values('Venomoth');
INSERT INTO pokemon(name) values('Diglett');
INSERT INTO pokemon(name) values('Dugtrio');
INSERT INTO pokemon(name) values('Meowth');
INSERT INTO pokemon(name) values('Persian');
INSERT INTO pokemon(name) values('Psyduck');
INSERT INTO pokemon(name) values('Golduck');
INSERT INTO pokemon(name) values('Mankey');
INSERT INTO pokemon(name) values('Primeape');
INSERT INTO pokemon(name) values('Growlithe');
INSERT INTO pokemon(name) values('Arcanine');
INSERT INTO pokemon(name) values('Poliwag');
INSERT INTO pokemon(name) values('Poliwhirl');
INSERT INTO pokemon(name) values('Poliwrath');
INSERT INTO pokemon(name) values('Abra');
INSERT INTO pokemon(name) values('Kadabra');
INSERT INTO pokemon(name) values('Alakazam');
INSERT INTO pokemon(name) values('Machop');
INSERT INTO pokemon(name) values('Machoke');
INSERT INTO pokemon(name) values('Machamp');
INSERT INTO pokemon(name) values('Bellsprout');
INSERT INTO pokemon(name) values('Weepinbell');
INSERT INTO pokemon(name) values('Victreebel');
INSERT INTO pokemon(name) values('Tentacool');
INSERT INTO pokemon(name) values('Tentacruel');
INSERT INTO pokemon(name) values('Geodude');
INSERT INTO pokemon(name) values('Graveler');
INSERT INTO pokemon(name) values('Golem');
INSERT INTO pokemon(name) values('Ponyta');
INSERT INTO pokemon(name) values('Rapidash');
INSERT INTO pokemon(name) values('Slowpoke');
INSERT INTO pokemon(name) values('Slowbro');
INSERT INTO pokemon(name) values('Magnemite');
INSERT INTO pokemon(name) values('Magneton');
INSERT INTO pokemon(name) values('Farfetch'd');
INSERT INTO pokemon(name) values('Doduo');
INSERT INTO pokemon(name) values('Dodrio');
INSERT INTO pokemon(name) values('Seel');
INSERT INTO pokemon(name) values('Dewgong');
INSERT INTO pokemon(name) values('Grimer');
INSERT INTO pokemon(name) values('Muk');
INSERT INTO pokemon(name) values('Shellder');
INSERT INTO pokemon(name) values('Cloyster');
INSERT INTO pokemon(name) values('Gastly');
INSERT INTO pokemon(name) values('Haunter');
INSERT INTO pokemon(name) values('Gengar');
INSERT INTO pokemon(name) values('Onix');
INSERT INTO pokemon(name) values('Drowzee');
INSERT INTO pokemon(name) values('Hypno');
INSERT INTO pokemon(name) values('Krabby');
INSERT INTO pokemon(name) values('Kingler');
INSERT INTO pokemon(name) values('Voltorb');
INSERT INTO pokemon(name) values('Electrode');
INSERT INTO pokemon(name) values('Exeggcute');
INSERT INTO pokemon(name) values('Exeggutor');
INSERT INTO pokemon(name) values('Cubone');
INSERT INTO pokemon(name) values('Marowak');
INSERT INTO pokemon(name) values('Hitmonlee');
INSERT INTO pokemon(name) values('Hitmonchan');
INSERT INTO pokemon(name) values('Lickitung');
INSERT INTO pokemon(name) values('Koffing');
INSERT INTO pokemon(name) values('Weezing');
INSERT INTO pokemon(name) values('Rhyhorn');
INSERT INTO pokemon(name) values('Rhydon');
INSERT INTO pokemon(name) values('Chansey');
INSERT INTO pokemon(name) values('Tangela');
INSERT INTO pokemon(name) values('Kangaskhan');
INSERT INTO pokemon(name) values('Horsea');
INSERT INTO pokemon(name) values('Seadra');
INSERT INTO pokemon(name) values('Goldeen');
INSERT INTO pokemon(name) values('Seaking');
INSERT INTO pokemon(name) values('Staryu');
INSERT INTO pokemon(name) values('Starmie');
INSERT INTO pokemon(name) values('Mr. Mime');
INSERT INTO pokemon(name) values('Scyther');
INSERT INTO pokemon(name) values('Jynx');
INSERT INTO pokemon(name) values('Electabuzz');
INSERT INTO pokemon(name) values('Magmar');
INSERT INTO pokemon(name) values('Pinsir');
INSERT INTO pokemon(name) values('Tauros');
INSERT INTO pokemon(name) values('Magikarp');
INSERT INTO pokemon(name) values('Gyarados');
INSERT INTO pokemon(name) values('Lapras');
INSERT INTO pokemon(name) values('Ditto');
INSERT INTO pokemon(name) values('Eevee');
INSERT INTO pokemon(name) values('Vaporeon');
INSERT INTO pokemon(name) values('Jolteon');
INSERT INTO pokemon(name) values('Flareon');
INSERT INTO pokemon(name) values('Porygon');
INSERT INTO pokemon(name) values('Omanyte');
INSERT INTO pokemon(name) values('Omastar');
INSERT INTO pokemon(name) values('Kabuto');
INSERT INTO pokemon(name) values('Kabutops');
INSERT INTO pokemon(name) values('Aerodactyl');
INSERT INTO pokemon(name) values('Snorlax');
INSERT INTO pokemon(name) values('Articuno');
INSERT INTO pokemon(name) values('Zapdos');
INSERT INTO pokemon(name) values('Moltres');
INSERT INTO pokemon(name) values('Dratini');
INSERT INTO pokemon(name) values('Dragonair');
INSERT INTO pokemon(name) values('Dragonite');
INSERT INTO pokemon(name) values('Mewtwo');
INSERT INTO pokemon(name) values('Mew');

/*Type*/
INSERT INTO type(type) values('Agua');
INSERT INTO type(type) values('Bicho');
INSERT INTO type(type) values('Dragón');
INSERT INTO type(type) values('Eléctrico');
INSERT INTO type(type) values('Fantasma');
INSERT INTO type(type) values('Fuego');
INSERT INTO type(type) values('Hielo');
INSERT INTO type(type) values('Lucha');
INSERT INTO type(type) values('Normal');
INSERT INTO type(type) values('Planta');
INSERT INTO type(type) values('Psíquico');
INSERT INTO type(type) values('Roca');
INSERT INTO type(type) values('Tierra');
INSERT INTO type(type) values('Veneno');
INSERT INTO type(type) values('Volador');
INSERT INTO type(type) values('Siniestro');
INSERT INTO type(type) values('Hada');
INSERT INTO type(type) values('Acero');

/*PokemonType*/
INSERT INTO pokemon_type(num_pokedex, id_type) values(1, 10);
INSERT INTO pokemon_type(num_pokedex, id_type) values(1, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(2, 10);
INSERT INTO pokemon_type(num_pokedex, id_type) values(2, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(3, 10);
INSERT INTO pokemon_type(num_pokedex, id_type) values(3, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(4, 6);
INSERT INTO pokemon_type(num_pokedex, id_type) values(5, 6);
INSERT INTO pokemon_type(num_pokedex, id_type) values(6, 6);
INSERT INTO pokemon_type(num_pokedex, id_type) values(6, 15);
INSERT INTO pokemon_type(num_pokedex, id_type) values(7, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(8, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(9, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(10, 2);
INSERT INTO pokemon_type(num_pokedex, id_type) values(11, 2);
INSERT INTO pokemon_type(num_pokedex, id_type) values(12, 2);
INSERT INTO pokemon_type(num_pokedex, id_type) values(12, 15);
INSERT INTO pokemon_type(num_pokedex, id_type) values(13, 2);
INSERT INTO pokemon_type(num_pokedex, id_type) values(13, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(14, 2);
INSERT INTO pokemon_type(num_pokedex, id_type) values(14, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(15, 2);
INSERT INTO pokemon_type(num_pokedex, id_type) values(15, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(16, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(16, 15);
INSERT INTO pokemon_type(num_pokedex, id_type) values(17, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(17, 15);
INSERT INTO pokemon_type(num_pokedex, id_type) values(18, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(18, 15);
INSERT INTO pokemon_type(num_pokedex, id_type) values(19, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(20, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(21, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(21, 15);
INSERT INTO pokemon_type(num_pokedex, id_type) values(22, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(22, 15);
INSERT INTO pokemon_type(num_pokedex, id_type) values(23, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(24, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(25, 4);
INSERT INTO pokemon_type(num_pokedex, id_type) values(26, 4);
INSERT INTO pokemon_type(num_pokedex, id_type) values(27, 13);
INSERT INTO pokemon_type(num_pokedex, id_type) values(28, 13);
INSERT INTO pokemon_type(num_pokedex, id_type) values(29, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(30, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(31, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(31, 13);
INSERT INTO pokemon_type(num_pokedex, id_type) values(32, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(33, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(34, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(34, 13);
INSERT INTO pokemon_type(num_pokedex, id_type) values(35, 17);
INSERT INTO pokemon_type(num_pokedex, id_type) values(36, 17);
INSERT INTO pokemon_type(num_pokedex, id_type) values(37, 6);
INSERT INTO pokemon_type(num_pokedex, id_type) values(38, 6);
INSERT INTO pokemon_type(num_pokedex, id_type) values(39, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(39, 17);
INSERT INTO pokemon_type(num_pokedex, id_type) values(40, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(40, 17);
INSERT INTO pokemon_type(num_pokedex, id_type) values(41, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(41, 15);
INSERT INTO pokemon_type(num_pokedex, id_type) values(42, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(42, 15);
INSERT INTO pokemon_type(num_pokedex, id_type) values(43, 10);
INSERT INTO pokemon_type(num_pokedex, id_type) values(43, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(44, 10);
INSERT INTO pokemon_type(num_pokedex, id_type) values(44, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(45, 10);
INSERT INTO pokemon_type(num_pokedex, id_type) values(45, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(46, 2);
INSERT INTO pokemon_type(num_pokedex, id_type) values(46, 10);
INSERT INTO pokemon_type(num_pokedex, id_type) values(47, 2);
INSERT INTO pokemon_type(num_pokedex, id_type) values(47, 10);
INSERT INTO pokemon_type(num_pokedex, id_type) values(48, 2);
INSERT INTO pokemon_type(num_pokedex, id_type) values(48, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(49, 2);
INSERT INTO pokemon_type(num_pokedex, id_type) values(49, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(50, 13);
INSERT INTO pokemon_type(num_pokedex, id_type) values(51, 13);
INSERT INTO pokemon_type(num_pokedex, id_type) values(52, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(53, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(54, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(55, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(56, 8);
INSERT INTO pokemon_type(num_pokedex, id_type) values(57, 8);
INSERT INTO pokemon_type(num_pokedex, id_type) values(58, 6);
INSERT INTO pokemon_type(num_pokedex, id_type) values(59, 6);
INSERT INTO pokemon_type(num_pokedex, id_type) values(60, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(61, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(62, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(62, 8);
INSERT INTO pokemon_type(num_pokedex, id_type) values(63, 11);
INSERT INTO pokemon_type(num_pokedex, id_type) values(64, 11);
INSERT INTO pokemon_type(num_pokedex, id_type) values(65, 11);
INSERT INTO pokemon_type(num_pokedex, id_type) values(66, 8);
INSERT INTO pokemon_type(num_pokedex, id_type) values(67, 8);
INSERT INTO pokemon_type(num_pokedex, id_type) values(68, 8);
INSERT INTO pokemon_type(num_pokedex, id_type) values(69, 10);
INSERT INTO pokemon_type(num_pokedex, id_type) values(69, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(70, 10);
INSERT INTO pokemon_type(num_pokedex, id_type) values(70, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(71, 10);
INSERT INTO pokemon_type(num_pokedex, id_type) values(71, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(72, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(72, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(73, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(73, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(74, 12);
INSERT INTO pokemon_type(num_pokedex, id_type) values(74, 13);
INSERT INTO pokemon_type(num_pokedex, id_type) values(75, 12);
INSERT INTO pokemon_type(num_pokedex, id_type) values(75, 13);
INSERT INTO pokemon_type(num_pokedex, id_type) values(76, 12);
INSERT INTO pokemon_type(num_pokedex, id_type) values(76, 13);
INSERT INTO pokemon_type(num_pokedex, id_type) values(77, 6);
INSERT INTO pokemon_type(num_pokedex, id_type) values(78, 6);
INSERT INTO pokemon_type(num_pokedex, id_type) values(79, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(79, 11);
INSERT INTO pokemon_type(num_pokedex, id_type) values(80, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(80, 11);
INSERT INTO pokemon_type(num_pokedex, id_type) values(81, 4);
INSERT INTO pokemon_type(num_pokedex, id_type) values(81, 18);
INSERT INTO pokemon_type(num_pokedex, id_type) values(82, 4);
INSERT INTO pokemon_type(num_pokedex, id_type) values(82, 18);
INSERT INTO pokemon_type(num_pokedex, id_type) values(83, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(83, 15);
INSERT INTO pokemon_type(num_pokedex, id_type) values(84, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(84, 15);
INSERT INTO pokemon_type(num_pokedex, id_type) values(85, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(85, 15);
INSERT INTO pokemon_type(num_pokedex, id_type) values(86, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(87, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(87, 7);
INSERT INTO pokemon_type(num_pokedex, id_type) values(88, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(89, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(90, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(91, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(91, 7);
INSERT INTO pokemon_type(num_pokedex, id_type) values(92, 5);
INSERT INTO pokemon_type(num_pokedex, id_type) values(92, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(93, 5);
INSERT INTO pokemon_type(num_pokedex, id_type) values(93, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(94, 5);
INSERT INTO pokemon_type(num_pokedex, id_type) values(94, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(95, 12);
INSERT INTO pokemon_type(num_pokedex, id_type) values(95, 13);
INSERT INTO pokemon_type(num_pokedex, id_type) values(96, 11);
INSERT INTO pokemon_type(num_pokedex, id_type) values(97, 11);
INSERT INTO pokemon_type(num_pokedex, id_type) values(98, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(99, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(100, 4);
INSERT INTO pokemon_type(num_pokedex, id_type) values(101, 4);
INSERT INTO pokemon_type(num_pokedex, id_type) values(102, 10);
INSERT INTO pokemon_type(num_pokedex, id_type) values(102, 11);
INSERT INTO pokemon_type(num_pokedex, id_type) values(103, 10);
INSERT INTO pokemon_type(num_pokedex, id_type) values(103, 11);
INSERT INTO pokemon_type(num_pokedex, id_type) values(104, 13);
INSERT INTO pokemon_type(num_pokedex, id_type) values(105, 13);
INSERT INTO pokemon_type(num_pokedex, id_type) values(106, 8);
INSERT INTO pokemon_type(num_pokedex, id_type) values(107, 8);
INSERT INTO pokemon_type(num_pokedex, id_type) values(108, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(109, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(110, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(111, 13);
INSERT INTO pokemon_type(num_pokedex, id_type) values(111, 12);
INSERT INTO pokemon_type(num_pokedex, id_type) values(112, 13);
INSERT INTO pokemon_type(num_pokedex, id_type) values(112, 12);
INSERT INTO pokemon_type(num_pokedex, id_type) values(113, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(114, 10);
INSERT INTO pokemon_type(num_pokedex, id_type) values(115, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(116, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(117, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(118, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(119, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(120, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(121, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(121, 11);
INSERT INTO pokemon_type(num_pokedex, id_type) values(122, 11);
INSERT INTO pokemon_type(num_pokedex, id_type) values(122, 17);
INSERT INTO pokemon_type(num_pokedex, id_type) values(123, 2);
INSERT INTO pokemon_type(num_pokedex, id_type) values(123, 15);
INSERT INTO pokemon_type(num_pokedex, id_type) values(124, 7);
INSERT INTO pokemon_type(num_pokedex, id_type) values(124, 11);
INSERT INTO pokemon_type(num_pokedex, id_type) values(125, 4);
INSERT INTO pokemon_type(num_pokedex, id_type) values(126, 6);
INSERT INTO pokemon_type(num_pokedex, id_type) values(127, 2);
INSERT INTO pokemon_type(num_pokedex, id_type) values(128, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(129, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(130, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(130, 15);
INSERT INTO pokemon_type(num_pokedex, id_type) values(131, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(131, 7);
INSERT INTO pokemon_type(num_pokedex, id_type) values(132, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(133, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(134, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(135, 4);
INSERT INTO pokemon_type(num_pokedex, id_type) values(136, 6);
INSERT INTO pokemon_type(num_pokedex, id_type) values(137, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(138, 12);
INSERT INTO pokemon_type(num_pokedex, id_type) values(138, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(139, 12);
INSERT INTO pokemon_type(num_pokedex, id_type) values(139, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(140, 12);
INSERT INTO pokemon_type(num_pokedex, id_type) values(140, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(141, 12);
INSERT INTO pokemon_type(num_pokedex, id_type) values(141, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(142, 12);
INSERT INTO pokemon_type(num_pokedex, id_type) values(142, 15);
INSERT INTO pokemon_type(num_pokedex, id_type) values(143, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(144, 7);
INSERT INTO pokemon_type(num_pokedex, id_type) values(144, 15);
INSERT INTO pokemon_type(num_pokedex, id_type) values(145, 4);
INSERT INTO pokemon_type(num_pokedex, id_type) values(145, 15);
INSERT INTO pokemon_type(num_pokedex, id_type) values(146, 6);
INSERT INTO pokemon_type(num_pokedex, id_type) values(146, 15);
INSERT INTO pokemon_type(num_pokedex, id_type) values(147, 3);
INSERT INTO pokemon_type(num_pokedex, id_type) values(148, 3);
INSERT INTO pokemon_type(num_pokedex, id_type) values(149, 3);
INSERT INTO pokemon_type(num_pokedex, id_type) values(149, 15);
INSERT INTO pokemon_type(num_pokedex, id_type) values(150, 11);
INSERT INTO pokemon_type(num_pokedex, id_type) values(151, 11);

/*PokemonDetail*/
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(1, 'Semilla', 6.9, 0.7, 'Monstruo-Planta', 87.5, 12.5, 'Pradera', 'Verde', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(2, 'Semilla', 13, 1, 'Monstruo-Planta', 87.5, 12.5, 'Pradera', 'Verde', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(3, 'Semilla', 100, 2, 'Monstruo-Planta', 87.5, 12.5, 'Pradera', 'Verde', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(4, 'Lagartija', 8.5, 0.6, 'Monstruo-Dragón', 87.5, 12.5, 'Montaña', 'Rojo', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(5, 'Llama', 19, 1.1, 'Monstruo-Dragón', 87.5, 12.5, 'Montaña', 'Rojo', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(6, 'Llama', 90.5, 1.7, 'Monstruo-Dragón', 87.5, 12.5, 'Montaña', 'Rojo', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(7, 'Tortuguita', 9, 0.5, 'Monstruo-Agua-1', 87.5, 12.5, 'Agua Dulce', 'Azul', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(8, 'Tortuga', 22.5, 1, 'Monstruo-Agua-1', 87.5, 12.5, 'Agua Dulce', 'Azul', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(9, 'Armazón', 85.5, 1.6, 'Monstruo-Agua-1', 87.5, 12.5, 'Agua Dulce', 'Azul', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(10, 'Gusano', 2.9, 0.3, 'Bicho', 50, 50, 'Bosque', 'Verde', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(11, 'Capullo', 9.9, 0.7, 'Bicho', 50, 50, 'Bosque', 'Verde', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(12, 'Mariposa', 32, 1.1, 'Bicho', 50, 50, 'Bosque', 'Blanco', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(13, 'Oruga', 3.2, 0.3, 'Bicho', 50, 50, 'Bosque', 'Marrón', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(14, 'Capullo', 10, 0.6, 'Bicho', 50, 50, 'Bosque', 'Amarillo', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(15, 'Abeja Veneno', 29.5, 1, 'Bicho', 50, 50, 'Bosque', 'Amarillo', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(16, 'Pajarito', 1.8, 0.3, 'Volador', 50, 50, 'Bosque', 'Marrón', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(17, 'Pájaro', 30, 1.1, 'Volador', 50, 50, 'Bosque', 'Marrón', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(18, 'Pájaro', 39.5, 1.5, 'Volador', 50, 50, 'Bosque', 'Marrón', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(19, 'Ratón', 3.5, 0.3, 'Campo', 50, 50, 'Pradera', 'Morado', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(20, 'Ratón', 18.5, 0.7, 'Campo', 50, 50, 'Pradera', 'Marrón', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(21, 'Pajarito', 2, 0.3, 'Volador', 50, 50, 'Campo', 'Marrón', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(22, 'Pico', 38, 1.2, 'Volador', 50, 50, 'Campo', 'Marrón', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(23, 'Serpiente', 6.9, 2, 'Campo-Dragón', 50, 50, 'Pradera', 'Morado', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(24, 'Cobra', 65, 3.5, 'Campo-Dragón', 50, 50, 'Pradera', 'Morado', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(25, 'Ratón', 6, 0.4, 'Campo-Hada', 50, 50, 'Bosque', 'Amarilo', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(26, 'Ratón', 30, 0.8, 'Campo-Hada', 50, 50, 'Bosque', 'Amarilo', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(27, 'Ratón', 12, 0.6, 'Campo', 50, 50, 'Campo', 'Amarilo', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(28, 'Ratón', 29.5, 1, 'Campo', 50, 50, 'Campo', 'Amarilo', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(29, 'Pin Veneno', 7, 0.4, 'Monstruo-Campo', 0, 100, 'Pradera', 'Azul', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(30, 'Pin Veneno', 20, 0.8, 'Desconocido', 0, 100, 'Pradera', 'Azul', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(31, 'Taladro', 60, 1.3, 'Desconocido', 0, 100, 'Pradera', 'Azul', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(32, 'Pin Veneno', 9, 0.5, 'Monstruo-Campo', 100, 0, 'Pradera', 'Morado', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(33, 'Pin Veneno', 19.5, 0.9, 'Monstruo-Campo', 100, 0, 'Pradera', 'Morado', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(34, 'Taladro', 62, 1.4, 'Monstruo-Campo', 100, 0, 'Pradera', 'Morado', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(35, 'Hada', 7.5, 0.6, 'Hada', 25, 75, 'Montaña', 'Rosa', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(36, 'Hada', 40, 1.3, 'Hada', 25, 75, 'Montaña', 'Rosa', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(37, 'Zorro', 9.9, 0.6, 'Campo', 25, 75, 'Pradera', 'Marrón', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(38, 'Zorro', 19.9, 1.1, 'Campo', 25, 75, 'Pradera', 'Amarillo', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(39, 'Globo', 5.5, 0.5, 'Hada', 25, 75, 'Pradera', 'Rosa', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(40, 'Globo', 12, 1, 'Hada', 25, 75, 'Pradera', 'Rosa', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(41, 'Murciélago', 7.5, 0.8, 'Volador', 50, 50, 'Caverna', 'Morado', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(42, 'Murciélago', 55, 1.6, 'Volador', 50, 50, 'Caverna', 'Morado', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(43, 'Hierbajo', 5.4, 0.5, 'Planta', 50, 50, 'Pradera', 'Azul', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(44, 'Hierbajo', 8.6, 0.8, 'Planta', 50, 50, 'Pradera', 'Azul', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(45, 'Flor', 18.6, 1.2, 'Planta', 50, 50, 'Pradera', 'Rojo', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(46, 'Hongo', 5.4, 0.3, 'Bicho-Planta', 50, 50, 'Bosque', 'Rojo', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(47, 'Hongo', 29.5, 1, 'Bicho-Planta', 50, 50, 'Bosque', 'Rojo', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(48, 'Insecto', 30, 1, 'Bicho', 50, 50, 'Bosque', 'Mroado', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(49, 'Pollila Venenosa', 12.5, 1.5, 'Bicho', 50, 50, 'Bosque', 'Morado', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(50, 'Topo', 0.8, 0.2, 'Campo', 50, 50, 'Caverna', 'Marrón', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(51, 'Topo', 33.3, 0.7, 'Campo', 50, 50, 'Caverna', 'Marrón', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(52, 'Gato Araña', 4.2, 0.4, 'Campo', 50, 50, 'Ciudad', 'Amarillo', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(53, 'Gato Fino', 32, 1, 'Campo', 50, 50, 'Ciudad', 'Amarillo', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(54, 'Pato', 19.6, 0.8, 'Campo-Agua-1', 50, 50, 'Agua Dulce', 'Amarillo', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(55, 'Pato', 76.6, 1.7, 'Agua-1-Campo', 50, 50, 'Agua Dulce', 'Azul', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(56, 'Mono Cerdo', 28, 0.5, 'Campo', 50, 50, 'Montaña', 'Marrón', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(57, 'Mono Cerdo', 32, 1, 'Campo', 50, 50, 'Montaña', 'Marrón', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(58, 'Perrito', 19, 0.7, 'Campo', 50, 50, 'Pradera', 'Marrón', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(59, 'Leyenda', 155, 1.9, 'Campo', 75, 25, 'Pradera', 'Marrón', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(60, 'Renacuajo', 12.4, 0.6, 'Agua-1', 50, 50, 'Agua Dulce', 'Azul', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(61, 'Renacuajo', 20, 1, 'Agua-1', 50, 50, 'Agua Dulce', 'Azul', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(62, 'Renacuajo', 54, 1.3, 'Agua-1', 50, 50, 'Agua Dulce', 'Azul', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(63, 'Psi', 19.5, 0.9, 'Humanoide', 75, 25, 'Ciudad', 'Amarillo', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(64, 'Psi', 56.5, 1.3, 'Humanoide', 75, 25, 'Ciudad', 'Amarillo', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(65, 'Psi', 48, 1.5, 'Humanoide', 75, 25, 'Ciudad', 'Amarillo', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(66, 'Superpoder', 19.5, 0.8, 'Humanoide', 75, 25, 'Montaña', 'Gris', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(67, 'Superpoder', 70.5, 1.5, 'Humanoide', 75, 25, 'Montaña', 'Gris', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(68, 'Superpoder', 130, 1.6, 'Humanoide', 75, 25, 'Montaña', 'Gris', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(69, 'Flor', 4, 0.7, 'Planta', 50, 50, 'Bosque', 'Verde', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(70, 'Matamoscas', 6.4, 1, 'Planta', 50, 50, 'Bosque', 'Verde', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(71, 'Matamoscas', 15.5, 1.7, 'Planta', 50, 50, 'Bosque', 'Verde', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(72, 'Medusa', 45.5, 0.9, 'Agua-3', 50, 50, 'Agua Salada', 'Azul', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(73, 'Medusa', 55, 1.6, 'Agua-3', 50, 50, 'Agua Salada', 'Azul', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(74, 'Roca', 20, 4, 'Mineral', 50, 50, 'Montaña', 'Marrón', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(75, 'Roca', 105, 1, 'Mineral', 50, 50, 'Montaña', 'Marrón', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(76, 'Megatón', 300, 1.4, 'Mineral', 50, 50, 'Montaña', 'Marrón', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(77, 'Caballo Fuego', 30, 1, 'Campo', 50, 50, 'Pradera', 'Amarillo', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(78, 'Caballo Fuego', 95, 1.7, 'Campo', 50, 50, 'Pradera', 'Amarillo', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(79, 'Atontado', 36, 1.2, 'Monstruo-Agua-1', 50, 50, 'Agua Dulce', 'Rosa', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(80, 'Ermitaño', 78.5, 1.6, 'Monstruo-Agua-1', 50, 50, 'Agua Dulce', 'Rosa', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(81, 'Imán', 6, 0.3, 'Mineral', 0, 0, 'Campo', 'Gris', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(82, 'Imán', 60, 1, 'Mineral', 0, 0, 'Campo', 'Gris', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(83, 'Pato Salvaje', 15, 0.8, 'Volador-Campo', 50, 50, 'Pradera', 'Marrón', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(84, 'Ave Gemela', 39.2, 1.4, 'Volador', 50, 50, 'Pradera', 'Marrón', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(85, 'Ave Triple', 85.2, 1.8, 'Volador', 50, 50, 'Pradera', 'Marrón', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(86, 'León Marino', 90, 1.1, 'Agua-1-Campo', 50, 50, 'Agua Salada', 'Blanco', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(87, 'León Marino', 120, 1.7, 'Agua-1-Campo', 50, 50, 'Agua Salada', 'Blanco', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(88, 'Lodo', 30, 0.9, 'Amorfo', 50, 50, 'Ciudad', 'Morado', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(89, 'Lodo', 30, 1.2, 'Amorfo', 50, 50, 'Ciudad', 'Morado', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(90, 'Bivaldo', 4, 0.3, 'Agua-3', 50, 50, 'Agua Salada', 'Morado', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(91, 'Bivaldo', 132.5, 1.5, 'Agua-3', 50, 50, 'Agua Salada', 'Morado', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(92, 'Gas', 0.1, 1.3, 'Amorfo', 50, 50, 'Caverna', 'Morado', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(93, 'Gas', 0.1, 1.6, 'Amorfo', 50, 50, 'Caverna', 'Morado', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(94, 'Sombra', 40.5, 1.5, 'Amorfo', 50, 50, 'Caverna', 'Morado', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(95, 'Serpiente Roca', 210, 8.8, 'Mineral', 50, 50, 'Caverna', 'Gris', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(96, 'Hipnosis', 32.4, 1, 'Humanoide', 50, 50, 'Pradera', 'Amarillo', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(97, 'Hipnosis', 75.6, 1.6, 'Humanoide', 50, 50, 'Pradera', 'Amarillo', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(98, 'Cangrejo', 6.5, 0.4, 'Agua-3', 50, 50, 'Agua Dulce', 'Rojo', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(99, 'Tenaza', 60, 1.3, 'Agua-3', 50, 50, 'Agua Dulce', 'Rojo', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(100, 'Bola', 10.4, 0.5, 'Mineral', 0, 0, 'Ciudad', 'Rojo', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(101, 'Bola', 66.6, 1.2, 'Mineral', 0, 0, 'Ciudad', 'Rojo', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(102, 'Huevo', 2.5, 0.4, 'Planta', 50, 50, 'Bosque', 'Rosa', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(103, 'Coco', 120, 2, 'Planta', 50, 50, 'Bosque', 'Amarillo', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(104, 'Solitario', 6.5, 0.4, 'Monstruo', 50, 50, 'Montaña', 'Marrón', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(105, 'Apilahueso', 45, 1, 'Monstruo', 50, 50, 'Montaña', 'Marrón', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(106, 'Patada', 49.8, 1.5, 'Humanoide', 100, 0, 'Ciudad', 'Marrón', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(107, 'Puñetazo', 50.2, 1.4, 'Humanoide', 100, 0, 'Ciudad', 'Marrón', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(108, 'Lametazo', 65.5, 1.2, 'Monstruo', 50, 50, 'Pradera', 'Rosa', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(109, 'Gas Venenoso', 1, 0.6, 'Amorfo', 50, 50, 'Ciudad', 'Morado', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(110, 'Gas Venenoso', 9.5, 1.2, 'Amorfo', 50, 50, 'Ciudad', 'Morado', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(111, 'Clavos', 115, 1, 'Monstruo-Campo', 50, 50, 'Campo', 'Gris', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(112, 'Taladro', 120, 1.9, 'Monstruo-Campo', 50, 50, 'Campo', 'Gris', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(113, 'Huevo', 34.6, 1.1, 'Hada', 0, 100, 'Ciudad', 'Rosa', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(114, 'Enredadera', 35, 1, 'Planta', 50, 50, 'Pradera', 'Azul', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(115, 'Maternal', 80, 2.2, 'Monstruo', 0, 100, 'Pradera', 'Marrón', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(116, 'Dragón', 8, 0.4, 'Agua-1-Dragón', 50, 50, 'Agua Salada', 'Azul', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(117, 'Dragón', 25, 1.2, 'Agua-1-Dragón', 50, 50, 'Agua Salada', 'Azul', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(118, 'Pez Color', 15, 0.6, 'Agua-2', 50, 50, 'Agua Dulce', 'Rojo', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(119, 'Pez Color', 39, 1.3, 'Agua-2', 50, 50, 'Agua Dulce', 'Rojo', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(120, 'Estrella', 34.5, 0.8, 'Agua-3', 0, 0, 'Agua Salada', 'Marrón', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(121, 'Misterioso', 80, 1.1, 'Agua-3', 0, 0, 'Agua Salada', 'Morado', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(122, 'Barrera', 54.5, 1.3, 'Humanoide', 50, 50, 'Ciudad', 'Rosa', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(123, 'Mantis', 56, 1.5, 'Bicho', 50, 50, 'Pradera', 'Verde', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(124, 'Forma Humana', 40.6, 1.4, 'Humanoide', 0, 100, 'Ciudad', 'Rojo', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(125, 'Eléctrico', 33, 1.1, 'Humanoide', 75, 25, 'Pradera', 'Amarillo', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(126, 'Escupefuego', 44.5, 1.3, 'Humanoide', 75, 25, 'Montaña', 'Rojo', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(127, 'Escarabajo', 55, 1.5, 'Bicho', 50, 50, 'Bosque', 'Marrón', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(128, 'Toro Bravo', 88.4, 1.4, 'Campo', 100, 0, 'Pradera', 'Marrón', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(129, 'Pez', 10, 0.9, 'Agua-2-Dragón', 50, 50, 'Agua Dulce', 'Rojo', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(130, 'Atrocidad', 235, 6.5, 'Agua-2-Dragón', 50, 50, 'Agua Dulce', 'Azul', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(131, 'Transporte', 220, 2.5, 'Monstruo-Agua-1', 50, 50, 'Agua Salada', 'Azul', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(132, 'Transformación', 4, 0.3, 'Ditto', 0, 0, 'Ciudad', 'Morado', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(133, 'Evolución', 6.5, 0.3, 'Campo', 87.5, 12.5, 'Ciudad', 'Marrón', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(134, 'Burbuja', 29, 1, 'Campo', 87.5, 12.5, 'Ciudad', 'Azul', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(135, 'Relámpago', 24.5, 0.8, 'Campo', 87.5, 12.5, 'Ciudad', 'Amarillo', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(136, 'Llama', 25, 0.9, 'Campo', 87.5, 12.5, 'Ciudad', 'Rojo', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(137, 'Virtual', 36.5, 0.8, 'Mineral', 0, 0, 'Ciudad', 'Rosa', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(138, 'Espiral', 7.5, 0.4, 'Agua-1-Agua-3', 87.5, 12.5, 'Agua Salada', 'Azul', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(139, 'Espiral', 35, 1, 'Agua-1-Agua-3', 87.5, 12.5, 'Agua Salada', 'Azul', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(140, 'Armazón', 11.5, 0.5, 'Agua-1-Agua-3', 87.5, 12.5, 'Agua Salada', 'Marrón', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(141, 'Armazón', 40.5, 1.3, 'Agua-1-Agua-3', 87.5, 12.5, 'Agua Salada', 'Marrón', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(142, 'Fósil', 59, 1.8, 'Volador', 87.5, 12.5, 'Montaña', 'Morado', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(143, 'Dormir', 460, 2.1, 'Monstruo', 87.5, 12.5, 'Montaña', 'Negro', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(144, 'Congelar', 55.4, 1.7, 'Desconocido', 0, 0, 'Raro', 'Azul', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(145, 'Eléctrico', 52.6, 1.7, 'Desconocido', 0, 0, 'Raro', 'Amarillo', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(146, 'Llama', 60, 2, 'Desconocido', 0, 0, 'Raro', 'Rojo', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(147, 'Dragón', 3.3, 1.8, 'Agua-1-Dragón', 50, 50, 'Agua Dulce', 'Azul', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(148, 'Dragón', 16.5, 4, 'Agua-1-Dragón', 50, 50, 'Agua Dulce', 'Azul', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(149, 'Dragón', 210, 2.2, 'Agua-1-Dragón', 50, 50, 'Agua Dulce', 'Marrón', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(150, 'Genético', 122, 2, 'Desconocido', 0, 0, 'Raro', 'Morado', 'Primera', 'NULL', 'NULL', 'NULL');
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(151, 'Nueva especie', 4, 0.4, 'Desconocido', 0, 0, 'Raro', 'Rosa', 'Primera', 'NULL', 'NULL', 'NULL');

/*EvolutionForm*/
INSERT INTO evolution_form(name) values('Nivel');
INSERT INTO evolution_form(name) values('Piedra agua');
INSERT INTO evolution_form(name) values('Piedra fuego');
INSERT INTO evolution_form(name) values('Piedra hoja');
INSERT INTO evolution_form(name) values('Piedra lunar');
INSERT INTO evolution_form(name) values('Piedra trueno');
INSERT INTO evolution_form(name) values('Intercambio');

/*EvolutionFrom*/
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 2, 1);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 3, 2);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 5, 4);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 6, 5);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 8, 7);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 9, 8);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 11, 10);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 12, 11);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 14, 13);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 15, 14);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 17, 16);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 18, 17);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 20, 19);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 22, 21);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 24, 23);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(6, 26, 25);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 28, 27);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 30, 29);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(5, 31, 30);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 33, 32);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(5, 34, 33);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(5, 36, 35);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(3, 38, 37);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(5, 40, 39);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 42, 41);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 44, 43);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(4, 45, 44);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 47, 46);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 49, 48);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 51, 50);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 53, 52);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 55, 54);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 57, 56);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(3, 59, 58);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 61, 60);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(2, 62, 61);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 64, 63);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(7, 65, 64);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 67, 66);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(7, 68, 67);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 70, 69);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(4, 71, 70);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 73, 72);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 75, 74);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(7, 76, 75);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 78, 77);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 80, 79);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 82, 81);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 85, 84);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 87, 86);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 89, 88);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(2, 91, 90);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 93, 92);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(7, 94, 93);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 97, 96);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 99, 98);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 101, 100);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(4, 103, 102);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 105, 104);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 110, 109);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 112, 111);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 117, 116);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 119, 118);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(2, 121, 120);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 130, 129);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(2, 134, 133);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(6, 135, 133);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(3, 136, 133);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 139, 138);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 141, 140);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 148, 147);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 149, 148);

/*BaseStat*/
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(1, 45, 49, 49, 65, 65, 45);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(2, 60, 62, 63, 80, 80, 60);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(3, 80, 82, 83, 100, 100, 80);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(4, 39, 52, 43, 60, 50, 65);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(5, 58, 64, 58, 80, 65, 80);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(6, 78, 84, 78, 109, 85, 100);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(7, 44, 48, 65, 50, 64, 43);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(8, 59, 63, 80, 65, 80, 58);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(9, 79, 83, 100, 85, 105, 78);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(10, 45, 30, 35, 20, 20, 45);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(11, 50, 20, 55, 25, 25, 30);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(12, 60, 45, 50, 90, 80, 70);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(13, 40, 35, 30, 20, 20, 50);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(14, 45, 25, 50, 25, 25, 35);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(15, 65, 90, 40, 45, 80, 75);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(16, 40, 45, 40, 35, 35, 56);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(17, 63, 60, 55, 50, 50, 71);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(18, 83, 80, 75, 70, 70, 101);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(19, 30, 56, 35, 25, 35, 72);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(20, 55, 81, 60, 50, 70, 97);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(21, 40, 60, 30, 31, 31, 70);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(22, 65, 90, 65, 61, 61, 100);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(23, 35, 60, 44, 40, 54, 55);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(24, 60, 95, 69, 65, 79, 80);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(25, 35, 55, 40, 50, 50, 90);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(26, 60, 90, 55, 90, 80, 110);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(27, 50, 75, 85, 20, 30, 40);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(28, 75, 100, 110, 45, 55, 65);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(29, 55, 47, 52, 40, 40, 41);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(30, 70, 62, 67, 55, 55, 56);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(31, 90, 92, 87, 75, 85, 76);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(32, 46, 57, 40, 40, 40, 50);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(33, 61, 72, 57, 55, 55, 65);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(34, 81, 102, 77, 85, 75, 85);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(35, 70, 45, 48, 60, 65, 35);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(36, 95, 70, 73, 95, 90, 60);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(37, 38, 41, 40, 50, 65, 65);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(38, 73, 76, 75, 81, 100, 100);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(39, 115, 45, 20, 45, 25, 20);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(40, 140, 70, 45, 85, 50, 45);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(41, 40, 45, 35, 30, 40, 55);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(42, 75, 80, 70, 65, 75, 90);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(43, 45, 50, 55, 75, 65, 30);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(44, 60, 65, 70, 85, 75, 40);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(45, 75, 80, 85, 110, 90, 50);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(46, 35, 70, 55, 45, 55, 25);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(47, 60, 95, 80, 60, 80, 30);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(48, 60, 55, 50, 40, 55, 45);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(49, 70, 65, 60, 90, 75, 90);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(50, 10, 55, 25, 35, 45, 95);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(51, 35, 100, 50, 50, 70, 120);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(52, 40, 45, 35, 40, 40, 90);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(53, 65, 70, 60, 65, 65, 115);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(54, 50, 52, 48, 65, 50, 55);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(55, 80, 82, 78, 95, 80, 85);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(56, 40, 80, 35, 35, 45, 70);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(57, 65, 105, 60, 60, 70, 95);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(58, 55, 70, 45, 70, 50, 60);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(59, 90, 110, 80, 100, 80, 95);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(60, 40, 50, 40, 40, 40, 90);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(61, 65, 65, 65, 50, 50, 90);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(62, 90, 95, 95, 70, 90, 70);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(63, 25, 20, 15, 105, 55, 90);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(64, 40, 35, 30, 120, 70, 105);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(65, 55, 50, 45, 135, 95, 120);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(66, 70, 80, 50, 35, 35, 35);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(67, 80, 100, 70, 50, 60, 45);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(68, 90, 130, 80, 65, 85, 55);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(69, 50, 75, 35, 70, 30, 40);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(70, 65, 90, 50, 85, 45, 55);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(71, 80, 105, 65, 100, 70, 70);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(72, 40, 40, 35, 50, 100, 70);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(73, 80, 70, 65, 80, 120, 100);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(74, 40, 80, 100, 30, 30, 20);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(75, 55, 95, 115, 45, 45, 35);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(76, 80, 120, 130, 55, 65, 45);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(77, 50, 85, 55, 65, 65, 90);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(78, 65, 100, 70, 80, 80, 105);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(79, 90, 65, 65, 40, 40, 15);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(80, 95, 75, 110, 100, 80, 30);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(81, 25, 35, 70, 95, 55, 45);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(82, 50, 60, 95, 120, 70, 70);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(83, 52, 90, 55, 58, 62, 60);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(84, 35, 85, 45, 35, 35, 75);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(85, 60, 110, 70, 60, 60, 110);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(86, 65, 45, 55, 45, 70, 45);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(87, 90, 70, 80, 70, 95, 70);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(88, 80, 80, 50, 40, 50, 25);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(89, 105, 105, 75, 65, 100, 50);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(90, 30, 65, 100, 45, 25, 40);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(91, 50, 95, 180, 85, 45, 70);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(92, 30, 35, 30, 100, 35, 80);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(93, 45, 50, 45, 115, 55, 95);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(94, 60, 65, 60, 130, 75, 110);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(95, 35, 45, 160, 30, 45, 70);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(96, 60, 48, 45, 43, 90, 42);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(97, 85, 73, 70, 73, 115, 67);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(98, 30, 105, 90, 25, 25, 50);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(99, 55, 130, 115, 50, 50, 75);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(100, 40, 30, 50, 55, 55, 100);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(101, 60, 50, 70, 80, 80, 150);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(102, 60, 40, 80, 60, 45, 40);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(103, 95, 95, 85, 125, 75, 55);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(104, 50, 50, 95, 40, 50, 35);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(105, 60, 80, 110, 50, 80, 45);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(106, 50, 120, 53, 35, 110, 87);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(107, 50, 105, 79, 35, 110, 76);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(108, 90, 55, 75, 60, 75, 30);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(109, 40, 65, 95, 60, 45, 35);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(110, 65, 90, 120, 85, 70, 60);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(111, 80, 85, 95, 30, 30, 25);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(112, 105, 130, 120, 45, 45, 40);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(113, 250, 5, 5, 35, 105, 50);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(114, 65, 55, 115, 100, 40, 60);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(115, 105, 95, 80, 40, 80, 90);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(116, 30, 40, 70, 70, 25, 60);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(117, 55, 65, 95, 95, 45, 85);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(118, 45, 67, 60, 35, 50, 63);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(119, 80, 92, 65, 65, 80, 68);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(120, 30, 45, 55, 70, 55, 85);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(121, 60, 75, 85, 100, 85, 115);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(122, 40, 45, 65, 100, 120, 90);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(123, 70, 110, 80, 55, 80, 105);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(124, 65, 50, 35, 115, 95, 95);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(125, 65, 83, 57, 95, 85, 105);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(126, 65, 95, 57, 100, 85, 93);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(127, 65, 125, 100, 55, 70, 85);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(128, 75, 100, 95, 40, 70, 110);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(129, 20, 10, 55, 15, 20, 80);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(130, 95, 125, 79, 60, 100, 81);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(131, 130, 85, 80, 85, 95, 60);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(132, 48, 48, 48, 48, 48, 48);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(133, 55, 55, 50, 45, 65, 55);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(134, 130, 65, 60, 110, 95, 65);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(135, 65, 65, 60, 110, 95, 130);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(136, 65, 130, 60, 95, 110, 65);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(137, 65, 60, 70, 85, 75, 40);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(138, 35, 40, 100, 90, 55, 35);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(139, 70, 60, 125, 115, 70, 55);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(140, 30, 80, 90, 55, 45, 55);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(141, 60, 115, 105, 65, 70, 80);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(142, 80, 105, 65, 60, 75, 130);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(143, 160, 110, 65, 65, 110, 30);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(144, 90, 85, 100, 95, 125, 85);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(145, 90, 90, 85, 125, 90, 100);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(146, 90, 100, 90, 125, 85, 90);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(147, 41, 64, 45, 50, 50, 50);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(148, 61, 84, 65, 70, 70, 70);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(149, 91, 134, 95, 100, 100, 80);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(150, 106, 110, 90, 154, 90, 130);
INSERT INTO base_stat(num_pokedex, ps, attack, defence, special_attack, special_defence, velocity) values(151, 100, 100, 100, 100, 100, 100);

/*MovementCategory*/
INSERT INTO movement_category(name) values('Físico');
INSERT INTO movement_category(name) values('Especial');
INSERT INTO movement_category(name) values('Efecto Estado');

/*Contest*/
INSERT INTO contest(name) values('Belleza');
INSERT INTO contest(name) values('Carisma');
INSERT INTO contest(name) values('Dulzura');
INSERT INTO contest(name) values('Dureza');
INSERT INTO contest(name) values('Ingenio');

/*Movement*/
INSERT INTO movement(name, id_type, id_movement_category, id_contest, description, secondary_effect, power, pp, movement.precision, priority) values('Burbuja', 1, 2, 3, 'Lanza burbujas en tres direcciones y causa daño a los enemigos a su alcance. También puede reducir su velocidad de desplazamiento.', 'Reducir la velocidad de los oponentes (10%)', 40, 30, 100, 0);
INSERT INTO movement(name, id_type, id_movement_category, id_contest, description, secondary_effect, power, pp, movement.precision, priority) values('Cascada', 1, 1, 4, 'El pokémon se lanza contra el enemigo a una velocidad asombrosa. También se puede utilizar para escalar una cascada.', 'Amedrentar al objetivo (20%)', 80, 15, 100, 0);
INSERT INTO movement(name, id_type, id_movement_category, id_contest, description, secondary_effect, power, pp, movement.precision, priority) values('Hidrobomba', 1, 2, 1, 'El enemigo es atacado por un gran volumen de agua lanzado bajo una gran presión.', 'null', 110, 5, 80, 0);

COMMIT;