CREATE DATABASE IF NOT EXISTS pokedexdb;

USE pokedexdb;

BEGIN;

/*Pokemon*/
INSERT INTO pokemon(name) values("Bulbasaur");
INSERT INTO pokemon(name) values("Ivysaur");
INSERT INTO pokemon(name) values("Venusaur");
INSERT INTO pokemon(name) values("Charmander");
INSERT INTO pokemon(name) values("Charmeleon");
INSERT INTO pokemon(name) values("Charizard");
INSERT INTO pokemon(name) values("Squirtle");
INSERT INTO pokemon(name) values("Wartortle");
INSERT INTO pokemon(name) values("Blastoise");
INSERT INTO pokemon(name) values("Caterpie");
INSERT INTO pokemon(name) values("Metapod");
INSERT INTO pokemon(name) values("Butterfree");
INSERT INTO pokemon(name) values("Weedle");
INSERT INTO pokemon(name) values("Kakuna");
INSERT INTO pokemon(name) values("Beedrill");
INSERT INTO pokemon(name) values("Pidgey");
INSERT INTO pokemon(name) values("Pidgeotto");
INSERT INTO pokemon(name) values("Pidgeot");
INSERT INTO pokemon(name) values("Rattata");
INSERT INTO pokemon(name) values("Raticate");
INSERT INTO pokemon(name) values("Spearow");
INSERT INTO pokemon(name) values("Fearow");
INSERT INTO pokemon(name) values("Ekans");
INSERT INTO pokemon(name) values("Arbok");
INSERT INTO pokemon(name) values("Pikachu");
INSERT INTO pokemon(name) values("Raichu");
INSERT INTO pokemon(name) values("Sandshrew");
INSERT INTO pokemon(name) values("Sandslash");
INSERT INTO pokemon(name) values("NidoranH");
INSERT INTO pokemon(name) values("Nidorina");
INSERT INTO pokemon(name) values("Nidoqueen");
INSERT INTO pokemon(name) values("NidoranM");
INSERT INTO pokemon(name) values("Nidorino");
INSERT INTO pokemon(name) values("Nidoking");
INSERT INTO pokemon(name) values("Clefairy");
INSERT INTO pokemon(name) values("Clefable");
INSERT INTO pokemon(name) values("Vulpix");
INSERT INTO pokemon(name) values("Ninetales");
INSERT INTO pokemon(name) values("Jigglypuff");
INSERT INTO pokemon(name) values("Wigglytuff");
INSERT INTO pokemon(name) values("Zubat");
INSERT INTO pokemon(name) values("Golbat");
INSERT INTO pokemon(name) values("Oddish");
INSERT INTO pokemon(name) values("Gloom");
INSERT INTO pokemon(name) values("Vileplume");
INSERT INTO pokemon(name) values("Paras");
INSERT INTO pokemon(name) values("Parasect");
INSERT INTO pokemon(name) values("Venonat");
INSERT INTO pokemon(name) values("Venomoth");
INSERT INTO pokemon(name) values("Diglett");
INSERT INTO pokemon(name) values("Dugtrio");
INSERT INTO pokemon(name) values("Meowth");
INSERT INTO pokemon(name) values("Persian");
INSERT INTO pokemon(name) values("Psyduck");
INSERT INTO pokemon(name) values("Golduck");
INSERT INTO pokemon(name) values("Mankey");
INSERT INTO pokemon(name) values("Primeape");
INSERT INTO pokemon(name) values("Growlithe");
INSERT INTO pokemon(name) values("Arcanine");
INSERT INTO pokemon(name) values("Poliwag");
INSERT INTO pokemon(name) values("Poliwhirl");
INSERT INTO pokemon(name) values("Poliwrath");
INSERT INTO pokemon(name) values("Abra");
INSERT INTO pokemon(name) values("Kadabra");
INSERT INTO pokemon(name) values("Alakazam");
INSERT INTO pokemon(name) values("Machop");
INSERT INTO pokemon(name) values("Machoke");
INSERT INTO pokemon(name) values("Machamp");
INSERT INTO pokemon(name) values("Bellsprout");
INSERT INTO pokemon(name) values("Weepinbell");
INSERT INTO pokemon(name) values("Victreebel");
INSERT INTO pokemon(name) values("Tentacool");
INSERT INTO pokemon(name) values("Tentacruel");
INSERT INTO pokemon(name) values("Geodude");
INSERT INTO pokemon(name) values("Graveler");
INSERT INTO pokemon(name) values("Golem");
INSERT INTO pokemon(name) values("Ponyta");
INSERT INTO pokemon(name) values("Rapidash");
INSERT INTO pokemon(name) values("Slowpoke");
INSERT INTO pokemon(name) values("Slowbro");
INSERT INTO pokemon(name) values("Magnemite");
INSERT INTO pokemon(name) values("Magneton");
INSERT INTO pokemon(name) values("Farfetch'd");
INSERT INTO pokemon(name) values("Doduo");
INSERT INTO pokemon(name) values("Dodrio");
INSERT INTO pokemon(name) values("Seel");
INSERT INTO pokemon(name) values("Dewgong");
INSERT INTO pokemon(name) values("Grimer");
INSERT INTO pokemon(name) values("Muk");
INSERT INTO pokemon(name) values("Shellder");
INSERT INTO pokemon(name) values("Cloyster");
INSERT INTO pokemon(name) values("Gastly");
INSERT INTO pokemon(name) values("Haunter");
INSERT INTO pokemon(name) values("Gengar");
INSERT INTO pokemon(name) values("Onix");
INSERT INTO pokemon(name) values("Drowzee");
INSERT INTO pokemon(name) values("Hypno");
INSERT INTO pokemon(name) values("Krabby");
INSERT INTO pokemon(name) values("Kingler");
INSERT INTO pokemon(name) values("Voltorb");
INSERT INTO pokemon(name) values("Electrode");
INSERT INTO pokemon(name) values("Exeggcute");
INSERT INTO pokemon(name) values("Exeggutor");
INSERT INTO pokemon(name) values("Cubone");
INSERT INTO pokemon(name) values("Marowak");
INSERT INTO pokemon(name) values("Hitmonlee");
INSERT INTO pokemon(name) values("Hitmonchan");
INSERT INTO pokemon(name) values("Lickitung");
INSERT INTO pokemon(name) values("Koffing");
INSERT INTO pokemon(name) values("Weezing");
INSERT INTO pokemon(name) values("Rhyhorn");
INSERT INTO pokemon(name) values("Rhydon");
INSERT INTO pokemon(name) values("Chansey");
INSERT INTO pokemon(name) values("Tangela");
INSERT INTO pokemon(name) values("Kangaskhan");
INSERT INTO pokemon(name) values("Horsea");
INSERT INTO pokemon(name) values("Seadra");
INSERT INTO pokemon(name) values("Goldeen");
INSERT INTO pokemon(name) values("Seaking");
INSERT INTO pokemon(name) values("Staryu");
INSERT INTO pokemon(name) values("Starmie");
INSERT INTO pokemon(name) values("Mr. Mime");
INSERT INTO pokemon(name) values("Scyther");
INSERT INTO pokemon(name) values("Jynx");
INSERT INTO pokemon(name) values("Electabuzz");
INSERT INTO pokemon(name) values("Magmar");
INSERT INTO pokemon(name) values("Pinsir");
INSERT INTO pokemon(name) values("Tauros");
INSERT INTO pokemon(name) values("Magikarp");
INSERT INTO pokemon(name) values("Gyarados");
INSERT INTO pokemon(name) values("Lapras");
INSERT INTO pokemon(name) values("Ditto");
INSERT INTO pokemon(name) values("Eevee");
INSERT INTO pokemon(name) values("Vaporeon");
INSERT INTO pokemon(name) values("Jolteon");
INSERT INTO pokemon(name) values("Flareon");
INSERT INTO pokemon(name) values("Porygon");
INSERT INTO pokemon(name) values("Omanyte");
INSERT INTO pokemon(name) values("Omastar");
INSERT INTO pokemon(name) values("Kabuto");
INSERT INTO pokemon(name) values("Kabutops");
INSERT INTO pokemon(name) values("Aerodactyl");
INSERT INTO pokemon(name) values("Snorlax");
INSERT INTO pokemon(name) values("Articuno");
INSERT INTO pokemon(name) values("Zapdos");
INSERT INTO pokemon(name) values("Moltres");
INSERT INTO pokemon(name) values("Dratini");
INSERT INTO pokemon(name) values("Dragonair");
INSERT INTO pokemon(name) values("Dragonite");
INSERT INTO pokemon(name) values("Mewtwo");
INSERT INTO pokemon(name) values("Mew");

/*Type*/
INSERT INTO type(type) values("Agua");
INSERT INTO type(type) values("Bicho");
INSERT INTO type(type) values("Dragón");
INSERT INTO type(type) values("Eléctrico");
INSERT INTO type(type) values("Fantasma");
INSERT INTO type(type) values("Fuego");
INSERT INTO type(type) values("Hielo");
INSERT INTO type(type) values("Lucha");
INSERT INTO type(type) values("Normal");
INSERT INTO type(type) values("Planta");
INSERT INTO type(type) values("Psíquico");
INSERT INTO type(type) values("Roca");
INSERT INTO type(type) values("Tierra");
INSERT INTO type(type) values("Veneno");
INSERT INTO type(type) values("Volador");
INSERT INTO type(type) values("Siniestro");
INSERT INTO type(type) values("Hada");
INSERT INTO type(type) values("Acero");

/*PokemonType*/
INSERT INTO pokemon_type(num_pokedex, id_type) values(1, 10);
INSERT INTO pokemon_type(num_pokedex, id_type) values(1, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(2, 10);
INSERT INTO pokemon_type(num_pokedex, id_type) values(2, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(3, 10);
INSERT INTO pokemon_type(num_pokedex, id_type) values(3, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(4, 6);
INSERT INTO pokemon_type(num_pokedex, id_type) values(5, 6);
INSERT INTO pokemon_type(num_pokedex, id_type) values(6, 6);
INSERT INTO pokemon_type(num_pokedex, id_type) values(6, 15);
INSERT INTO pokemon_type(num_pokedex, id_type) values(7, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(8, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(9, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(10, 2);
INSERT INTO pokemon_type(num_pokedex, id_type) values(11, 2);
INSERT INTO pokemon_type(num_pokedex, id_type) values(12, 2);
INSERT INTO pokemon_type(num_pokedex, id_type) values(12, 15);
INSERT INTO pokemon_type(num_pokedex, id_type) values(13, 2);
INSERT INTO pokemon_type(num_pokedex, id_type) values(13, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(14, 2);
INSERT INTO pokemon_type(num_pokedex, id_type) values(14, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(15, 2);
INSERT INTO pokemon_type(num_pokedex, id_type) values(15, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(16, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(16, 15);
INSERT INTO pokemon_type(num_pokedex, id_type) values(17, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(17, 15);
INSERT INTO pokemon_type(num_pokedex, id_type) values(18, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(18, 15);
INSERT INTO pokemon_type(num_pokedex, id_type) values(19, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(20, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(21, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(21, 15);
INSERT INTO pokemon_type(num_pokedex, id_type) values(22, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(22, 15);
INSERT INTO pokemon_type(num_pokedex, id_type) values(23, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(24, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(25, 4);
INSERT INTO pokemon_type(num_pokedex, id_type) values(26, 4);
INSERT INTO pokemon_type(num_pokedex, id_type) values(27, 13);
INSERT INTO pokemon_type(num_pokedex, id_type) values(28, 13);
INSERT INTO pokemon_type(num_pokedex, id_type) values(29, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(30, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(31, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(31, 13);
INSERT INTO pokemon_type(num_pokedex, id_type) values(32, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(33, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(34, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(34, 13);
INSERT INTO pokemon_type(num_pokedex, id_type) values(35, 17);
INSERT INTO pokemon_type(num_pokedex, id_type) values(36, 17);
INSERT INTO pokemon_type(num_pokedex, id_type) values(37, 6);
INSERT INTO pokemon_type(num_pokedex, id_type) values(38, 6);
INSERT INTO pokemon_type(num_pokedex, id_type) values(39, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(39, 17);
INSERT INTO pokemon_type(num_pokedex, id_type) values(40, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(40, 17);
INSERT INTO pokemon_type(num_pokedex, id_type) values(41, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(41, 15);
INSERT INTO pokemon_type(num_pokedex, id_type) values(42, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(42, 15);
INSERT INTO pokemon_type(num_pokedex, id_type) values(43, 10);
INSERT INTO pokemon_type(num_pokedex, id_type) values(43, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(44, 10);
INSERT INTO pokemon_type(num_pokedex, id_type) values(44, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(45, 10);
INSERT INTO pokemon_type(num_pokedex, id_type) values(45, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(46, 2);
INSERT INTO pokemon_type(num_pokedex, id_type) values(46, 10);
INSERT INTO pokemon_type(num_pokedex, id_type) values(47, 2);
INSERT INTO pokemon_type(num_pokedex, id_type) values(47, 10);
INSERT INTO pokemon_type(num_pokedex, id_type) values(48, 2);
INSERT INTO pokemon_type(num_pokedex, id_type) values(48, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(49, 2);
INSERT INTO pokemon_type(num_pokedex, id_type) values(49, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(50, 13);
INSERT INTO pokemon_type(num_pokedex, id_type) values(51, 13);
INSERT INTO pokemon_type(num_pokedex, id_type) values(52, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(53, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(54, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(55, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(56, 8);
INSERT INTO pokemon_type(num_pokedex, id_type) values(57, 8);
INSERT INTO pokemon_type(num_pokedex, id_type) values(58, 6);
INSERT INTO pokemon_type(num_pokedex, id_type) values(59, 6);
INSERT INTO pokemon_type(num_pokedex, id_type) values(60, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(61, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(62, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(62, 8);
INSERT INTO pokemon_type(num_pokedex, id_type) values(63, 11);
INSERT INTO pokemon_type(num_pokedex, id_type) values(64, 11);
INSERT INTO pokemon_type(num_pokedex, id_type) values(65, 11);
INSERT INTO pokemon_type(num_pokedex, id_type) values(66, 8);
INSERT INTO pokemon_type(num_pokedex, id_type) values(67, 8);
INSERT INTO pokemon_type(num_pokedex, id_type) values(68, 8);
INSERT INTO pokemon_type(num_pokedex, id_type) values(69, 10);
INSERT INTO pokemon_type(num_pokedex, id_type) values(69, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(70, 10);
INSERT INTO pokemon_type(num_pokedex, id_type) values(70, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(71, 10);
INSERT INTO pokemon_type(num_pokedex, id_type) values(71, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(72, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(72, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(73, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(73, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(74, 12);
INSERT INTO pokemon_type(num_pokedex, id_type) values(74, 13);
INSERT INTO pokemon_type(num_pokedex, id_type) values(75, 12);
INSERT INTO pokemon_type(num_pokedex, id_type) values(75, 13);
INSERT INTO pokemon_type(num_pokedex, id_type) values(76, 12);
INSERT INTO pokemon_type(num_pokedex, id_type) values(76, 13);
INSERT INTO pokemon_type(num_pokedex, id_type) values(77, 6);
INSERT INTO pokemon_type(num_pokedex, id_type) values(78, 6);
INSERT INTO pokemon_type(num_pokedex, id_type) values(79, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(79, 11);
INSERT INTO pokemon_type(num_pokedex, id_type) values(80, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(80, 11);
INSERT INTO pokemon_type(num_pokedex, id_type) values(81, 4);
INSERT INTO pokemon_type(num_pokedex, id_type) values(81, 18);
INSERT INTO pokemon_type(num_pokedex, id_type) values(82, 4);
INSERT INTO pokemon_type(num_pokedex, id_type) values(82, 18);
INSERT INTO pokemon_type(num_pokedex, id_type) values(83, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(83, 15);
INSERT INTO pokemon_type(num_pokedex, id_type) values(84, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(84, 15);
INSERT INTO pokemon_type(num_pokedex, id_type) values(85, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(85, 15);
INSERT INTO pokemon_type(num_pokedex, id_type) values(86, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(87, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(87, 7);
INSERT INTO pokemon_type(num_pokedex, id_type) values(88, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(89, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(90, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(91, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(91, 7);
INSERT INTO pokemon_type(num_pokedex, id_type) values(92, 5);
INSERT INTO pokemon_type(num_pokedex, id_type) values(92, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(93, 5);
INSERT INTO pokemon_type(num_pokedex, id_type) values(93, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(94, 5);
INSERT INTO pokemon_type(num_pokedex, id_type) values(94, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(95, 12);
INSERT INTO pokemon_type(num_pokedex, id_type) values(95, 13);
INSERT INTO pokemon_type(num_pokedex, id_type) values(96, 11);
INSERT INTO pokemon_type(num_pokedex, id_type) values(97, 11);
INSERT INTO pokemon_type(num_pokedex, id_type) values(98, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(99, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(100, 4);
INSERT INTO pokemon_type(num_pokedex, id_type) values(101, 4);
INSERT INTO pokemon_type(num_pokedex, id_type) values(102, 10);
INSERT INTO pokemon_type(num_pokedex, id_type) values(102, 11);
INSERT INTO pokemon_type(num_pokedex, id_type) values(103, 10);
INSERT INTO pokemon_type(num_pokedex, id_type) values(103, 11);
INSERT INTO pokemon_type(num_pokedex, id_type) values(104, 13);
INSERT INTO pokemon_type(num_pokedex, id_type) values(105, 13);
INSERT INTO pokemon_type(num_pokedex, id_type) values(106, 8);
INSERT INTO pokemon_type(num_pokedex, id_type) values(107, 8);
INSERT INTO pokemon_type(num_pokedex, id_type) values(108, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(109, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(110, 14);
INSERT INTO pokemon_type(num_pokedex, id_type) values(111, 13);
INSERT INTO pokemon_type(num_pokedex, id_type) values(111, 12);
INSERT INTO pokemon_type(num_pokedex, id_type) values(112, 13);
INSERT INTO pokemon_type(num_pokedex, id_type) values(112, 12);
INSERT INTO pokemon_type(num_pokedex, id_type) values(113, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(114, 10);
INSERT INTO pokemon_type(num_pokedex, id_type) values(115, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(116, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(117, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(118, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(119, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(120, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(121, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(121, 11);
INSERT INTO pokemon_type(num_pokedex, id_type) values(122, 11);
INSERT INTO pokemon_type(num_pokedex, id_type) values(122, 17);
INSERT INTO pokemon_type(num_pokedex, id_type) values(123, 2);
INSERT INTO pokemon_type(num_pokedex, id_type) values(123, 15);
INSERT INTO pokemon_type(num_pokedex, id_type) values(124, 7);
INSERT INTO pokemon_type(num_pokedex, id_type) values(124, 11);
INSERT INTO pokemon_type(num_pokedex, id_type) values(125, 4);
INSERT INTO pokemon_type(num_pokedex, id_type) values(126, 6);
INSERT INTO pokemon_type(num_pokedex, id_type) values(127, 2);
INSERT INTO pokemon_type(num_pokedex, id_type) values(128, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(129, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(130, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(130, 15);
INSERT INTO pokemon_type(num_pokedex, id_type) values(131, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(131, 7);
INSERT INTO pokemon_type(num_pokedex, id_type) values(132, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(133, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(134, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(135, 4);
INSERT INTO pokemon_type(num_pokedex, id_type) values(136, 6);
INSERT INTO pokemon_type(num_pokedex, id_type) values(137, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(138, 12);
INSERT INTO pokemon_type(num_pokedex, id_type) values(138, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(139, 12);
INSERT INTO pokemon_type(num_pokedex, id_type) values(139, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(140, 12);
INSERT INTO pokemon_type(num_pokedex, id_type) values(140, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(141, 12);
INSERT INTO pokemon_type(num_pokedex, id_type) values(141, 1);
INSERT INTO pokemon_type(num_pokedex, id_type) values(142, 12);
INSERT INTO pokemon_type(num_pokedex, id_type) values(142, 15);
INSERT INTO pokemon_type(num_pokedex, id_type) values(143, 9);
INSERT INTO pokemon_type(num_pokedex, id_type) values(144, 7);
INSERT INTO pokemon_type(num_pokedex, id_type) values(144, 15);
INSERT INTO pokemon_type(num_pokedex, id_type) values(145, 4);
INSERT INTO pokemon_type(num_pokedex, id_type) values(145, 15);
INSERT INTO pokemon_type(num_pokedex, id_type) values(146, 6);
INSERT INTO pokemon_type(num_pokedex, id_type) values(146, 15);
INSERT INTO pokemon_type(num_pokedex, id_type) values(147, 3);
INSERT INTO pokemon_type(num_pokedex, id_type) values(148, 3);
INSERT INTO pokemon_type(num_pokedex, id_type) values(149, 3);
INSERT INTO pokemon_type(num_pokedex, id_type) values(149, 15);
INSERT INTO pokemon_type(num_pokedex, id_type) values(150, 11);
INSERT INTO pokemon_type(num_pokedex, id_type) values(151, 11);

/*PokemonDetail*/
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(1, "Semilla", 6.9, 0.7, "Monstruo-Planta", 87.5, 12.5, "Pradera", "Verde", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(2, "Semilla", 13, 1, "Monstruo-Planta", 87.5, 12.5, "Pradera", "Verde", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(3, "Semilla", 100, 2, "Monstruo-Planta", 87.5, 12.5, "Pradera", "Verde", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(4, "Lagartija", 8.5, 0.6, "Monstruo-Dragón", 87.5, 12.5, "Montaña", "Rojo", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(5, "Llama", 19, 1.1, "Monstruo-Dragón", 87.5, 12.5, "Montaña", "Rojo", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(6, "Llama", 90.5, 1.7, "Monstruo-Dragón", 87.5, 12.5, "Montaña", "Rojo", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(7, "Tortuguita", 9, 0.5, "Monstruo-Agua-1", 87.5, 12.5, "Agua Dulce", "Azul", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(8, "Tortuga", 22.5, 1, "Monstruo-Agua-1", 87.5, 12.5, "Agua Dulce", "Azul", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(9, "Armazón", 85.5, 1.6, "Monstruo-Agua-1", 87.5, 12.5, "Agua Dulce", "Azul", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(10, "Gusano", 2.9, 0.3, "Bicho", 50, 50, "Bosque", "Verde", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(11, "Capullo", 9.9, 0.7, "Bicho", 50, 50, "Bosque", "Verde", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(12, "Mariposa", 32, 1.1, "Bicho", 50, 50, "Bosque", "Blanco", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(13, "Oruga", 3.2, 0.3, "Bicho", 50, 50, "Bosque", "Marrón", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(14, "Capullo", 10, 0.6, "Bicho", 50, 50, "Bosque", "Amarillo", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(15, "Abeja Veneno", 29.5, 1, "Bicho", 50, 50, "Bosque", "Amarillo", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(16, "Pajarito", 1.8, 0.3, "Volador", 50, 50, "Bosque", "Marrón", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(17, "Pájaro", 30, 1.1, "Volador", 50, 50, "Bosque", "Marrón", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(18, "Pájaro", 39.5, 1.5, "Volador", 50, 50, "Bosque", "Marrón", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(19, "Ratón", 3.5, 0.3, "Campo", 50, 50, "Pradera", "Morado", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(20, "Ratón", 18.5, 0.7, "Campo", 50, 50, "Pradera", "Marrón", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(21, "Pajarito", 2, 0.3, "Volador", 50, 50, "Campo", "Marrón", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(22, "Pico", 38, 1.2, "Volador", 50, 50, "Campo", "Marrón", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(23, "Serpiente", 6.9, 2, "Campo-Dragón", 50, 50, "Pradera", "Morado", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(24, "Cobra", 65, 3.5, "Campo-Dragón", 50, 50, "Pradera", "Morado", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(25, "Ratón", 6, 0.4, "Campo-Hada", 50, 50, "Bosque", "Amarilo", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(26, "Ratón", 30, 0.8, "Campo-Hada", 50, 50, "Bosque", "Amarilo", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(27, "Ratón", 12, 0.6, "Campo", 50, 50, "Campo", "Amarilo", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(28, "Ratón", 29.5, 1, "Campo", 50, 50, "Campo", "Amarilo", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(29, "Pin Veneno", 7, 0.4, "Monstruo-Campo", 0, 100, "Pradera", "Azul", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(30, "Pin Veneno", 20, 0.8, "Desconocido", 0, 100, "Pradera", "Azul", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(31, "Taladro", 60, 1.3, "Desconocido", 0, 100, "Pradera", "Azul", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(32, "Pin Veneno", 9, 0.5, "Monstruo-Campo", 100, 0, "Pradera", "Morado", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(33, "Pin Veneno", 19.5, 0.9, "Monstruo-Campo", 100, 0, "Pradera", "Morado", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(34, "Taladro", 62, 1.4, "Monstruo-Campo", 100, 0, "Pradera", "Morado", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(35, "Hada", 7.5, 0.6, "Hada", 25, 75, "Montaña", "Rosa", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(36, "Hada", 40, 1.3, "Hada", 25, 75, "Montaña", "Rosa", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(37, "Zorro", 9.9, 0.6, "Campo", 25, 75, "Pradera", "Marrón", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(38, "Zorro", 19.9, 1.1, "Campo", 25, 75, "Pradera", "Amarillo", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(39, "Globo", 5.5, 0.5, "Hada", 25, 75, "Pradera", "Rosa", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(40, "Globo", 12, 1, "Hada", 25, 75, "Pradera", "Rosa", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(41, "Murciélago", 7.5, 0.8, "Volador", 50, 50, "Caverna", "Morado", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(42, "Murciélago", 55, 1.6, "Volador", 50, 50, "Caverna", "Morado", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(43, "Hierbajo", 5.4, 0.5, "Planta", 50, 50, "Pradera", "Azul", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(44, "Hierbajo", 8.6, 0.8, "Planta", 50, 50, "Pradera", "Azul", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(45, "Flor", 18.6, 1.2, "Planta", 50, 50, "Pradera", "Rojo", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(46, "Hongo", 5.4, 0.3, "Bicho-Planta", 50, 50, "Bosque", "Rojo", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(47, "Hongo", 29.5, 1, "Bicho-Planta", 50, 50, "Bosque", "Rojo", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(48, "Insecto", 30, 1, "Bicho", 50, 50, "Bosque", "Mroado", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(49, "Pollila Venenosa", 12.5, 1.5, "Bicho", 50, 50, "Bosque", "Morado", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(50, "Topo", 0.8, 0.2, "Campo", 50, 50, "Caverna", "Marrón", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(51, "Topo", 33.3, 0.7, "Campo", 50, 50, "Caverna", "Marrón", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(52, "Gato Araña", 4.2, 0.4, "Campo", 50, 50, "Ciudad", "Amarillo", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(53, "Gato Fino", 32, 1, "Campo", 50, 50, "Ciudad", "Amarillo", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(54, "Pato", 19.6, 0.8, "Campo-Agua-1", 50, 50, "Agua Dulce", "Amarillo", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(55, "Pato", 76.6, 1.7, "Agua-1-Campo", 50, 50, "Agua Dulce", "Azul", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(56, "Mono Cerdo", 28, 0.5, "Campo", 50, 50, "Montaña", "Marrón", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(57, "Mono Cerdo", 32, 1, "Campo", 50, 50, "Montaña", "Marrón", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(58, "Perrito", 19, 0.7, "Campo", 50, 50, "Pradera", "Marrón", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(59, "Leyenda", 155, 1.9, "Campo", 75, 25, "Pradera", "Marrón", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(60, "Renacuajo", 12.4, 0.6, "Agua-1", 50, 50, "Agua Dulce", "Azul", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(61, "Renacuajo", 20, 1, "Agua-1", 50, 50, "Agua Dulce", "Azul", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(62, "Renacuajo", 54, 1.3, "Agua-1", 50, 50, "Agua Dulce", "Azul", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(63, "Psi", 19.5, 0.9, "Humanoide", 75, 25, "Ciudad", "Amarillo", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(64, "Psi", 56.5, 1.3, "Humanoide", 75, 25, "Ciudad", "Amarillo", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(65, "Psi", 48, 1.5, "Humanoide", 75, 25, "Ciudad", "Amarillo", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(66, "Superpoder", 19.5, 0.8, "Humanoide", 75, 25, "Montaña", "Gris", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(67, "Superpoder", 70.5, 1.5, "Humanoide", 75, 25, "Montaña", "Gris", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(68, "Superpoder", 130, 1.6, "Humanoide", 75, 25, "Montaña", "Gris", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(69, "Flor", 4, 0.7, "Planta", 50, 50, "Bosque", "Verde", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(70, "Matamoscas", 6.4, 1, "Planta", 50, 50, "Bosque", "Verde", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(71, "Matamoscas", 15.5, 1.7, "Planta", 50, 50, "Bosque", "Verde", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(72, "Medusa", 45.5, 0.9, "Agua-3", 50, 50, "Agua Salada", "Azul", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(73, "Medusa", 55, 1.6, "Agua-3", 50, 50, "Agua Salada", "Azul", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(74, "Roca", 20, 4, "Mineral", 50, 50, "Montaña", "Marrón", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(75, "Roca", 105, 1, "Mineral", 50, 50, "Montaña", "Marrón", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(76, "Megatón", 300, 1.4, "Mineral", 50, 50, "Montaña", "Marrón", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(77, "Caballo Fuego", 30, 1, "Campo", 50, 50, "Pradera", "Amarillo", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(78, "Caballo Fuego", 95, 1.7, "Campo", 50, 50, "Pradera", "Amarillo", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(79, "Atontado", 36, 1.2, "Monstruo-Agua-1", 50, 50, "Agua Dulce", "Rosa", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(80, "Ermitaño", 78.5, 1.6, "Monstruo-Agua-1", 50, 50, "Agua Dulce", "Rosa", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(81, "Imán", 6, 0.3, "Mineral", 0, 0, "Campo", "Gris", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(82, "Imán", 60, 1, "Mineral", 0, 0, "Campo", "Gris", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(83, "Pato Salvaje", 15, 0.8, "Volador-Campo", 50, 50, "Pradera", "Marrón", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(84, "Ave Gemela", 39.2, 1.4, "Volador", 50, 50, "Pradera", "Marrón", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(85, "Ave Triple", 85.2, 1.8, "Volador", 50, 50, "Pradera", "Marrón", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(86, "León Marino", 90, 1.1, "Agua-1-Campo", 50, 50, "Agua Salada", "Blanco", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(87, "León Marino", 120, 1.7, "Agua-1-Campo", 50, 50, "Agua Salada", "Blanco", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(88, "Lodo", 30, 0.9, "Amorfo", 50, 50, "Ciudad", "Morado", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(89, "Lodo", 30, 1.2, "Amorfo", 50, 50, "Ciudad", "Morado", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(90, "Bivaldo", 4, 0.3, "Agua-3", 50, 50, "Agua Salada", "Morado", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(91, "Bivaldo", 132.5, 1.5, "Agua-3", 50, 50, "Agua Salada", "Morado", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(92, "Gas", 0.1, 1.3, "Amorfo", 50, 50, "Caverna", "Morado", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(93, "Gas", 0.1, 1.6, "Amorfo", 50, 50, "Caverna", "Morado", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(94, "Sombra", 40.5, 1.5, "Amorfo", 50, 50, "Caverna", "Morado", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(95, "Serpiente Roca", 210, 8.8, "Mineral", 50, 50, "Caverna", "Gris", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(96, "Hipnosis", 32.4, 1, "Humanoide", 50, 50, "Pradera", "Amarillo", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(97, "Hipnosis", 75.6, 1.6, "Humanoide", 50, 50, "Pradera", "Amarillo", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(98, "Cangrejo", 6.5, 0.4, "Agua-3", 50, 50, "Agua Dulce", "Rojo", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(99, "Tenaza", 60, 1.3, "Agua-3", 50, 50, "Agua Dulce", "Rojo", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(100, "Bola", 10.4, 0.5, "Mineral", 0, 0, "Ciudad", "Rojo", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(101, "Bola", 66.6, 1.2, "Mineral", 0, 0, "Ciudad", "Rojo", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(102, "Huevo", 2.5, 0.4, "Planta", 50, 50, "Bosque", "Rosa", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(103, "Coco", 120, 2, "Planta", 50, 50, "Bosque", "Amarillo", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(104, "Solitario", 6.5, 0.4, "Monstruo", 50, 50, "Montaña", "Marrón", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(105, "Apilahueso", 45, 1, "Monstruo", 50, 50, "Montaña", "Marrón", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(106, "Patada", 49.8, 1.5, "Humanoide", 100, 0, "Ciudad", "Marrón", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(107, "Puñetazo", 50.2, 1.4, "Humanoide", 100, 0, "Ciudad", "Marrón", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(108, "Lametazo", 65.5, 1.2, "Monstruo", 50, 50, "Pradera", "Rosa", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(109, "Gas Venenoso", 1, 0.6, "Amorfo", 50, 50, "Ciudad", "Morado", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(110, "Gas Venenoso", 9.5, 1.2, "Amorfo", 50, 50, "Ciudad", "Morado", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(111, "Clavos", 115, 1, "Monstruo-Campo", 50, 50, "Campo", "Gris", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(112, "Taladro", 120, 1.9, "Monstruo-Campo", 50, 50, "Campo", "Gris", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(113, "Huevo", 34.6, 1.1, "Hada", 0, 100, "Ciudad", "Rosa", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(114, "Enredadera", 35, 1, "Planta", 50, 50, "Pradera", "Azul", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(115, "Maternal", 80, 2.2, "Monstruo", 0, 100, "Pradera", "Marrón", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(116, "Dragón", 8, 0.4, "Agua-1-Dragón", 50, 50, "Agua Salada", "Azul", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(117, "Dragón", 25, 1.2, "Agua-1-Dragón", 50, 50, "Agua Salada", "Azul", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(118, "Pez Color", 15, 0.6, "Agua-2", 50, 50, "Agua Dulce", "Rojo", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(119, "Pez Color", 39, 1.3, "Agua-2", 50, 50, "Agua Dulce", "Rojo", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(120, "Estrella", 34.5, 0.8, "Agua-3", 0, 0, "Agua Salada", "Marrón", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(121, "Misterioso", 80, 1.1, "Agua-3", 0, 0, "Agua Salada", "Morado", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(122, "Barrera", 54.5, 1.3, "Humanoide", 50, 50, "Ciudad", "Rosa", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(123, "Mantis", 56, 1.5, "Bicho", 50, 50, "Pradera", "Verde", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(124, "Forma Humana", 40.6, 1.4, "Humanoide", 0, 100, "Ciudad", "Rojo", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(125, "Eléctrico", 33, 1.1, "Humanoide", 75, 25, "Pradera", "Amarillo", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(126, "Escupefuego", 44.5, 1.3, "Humanoide", 75, 25, "Montaña", "Rojo", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(127, "Escarabajo", 55, 1.5, "Bicho", 50, 50, "Bosque", "Marrón", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(128, "Toro Bravo", 88.4, 1.4, "Campo", 100, 0, "Pradera", "Marrón", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(129, "Pez", 10, 0.9, "Agua-2-Dragón", 50, 50, "Agua Dulce", "Rojo", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(130, "Atrocidad", 235, 6.5, "Agua-2-Dragón", 50, 50, "Agua Dulce", "Azul", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(131, "Transporte", 220, 2.5, "Monstruo-Agua-1", 50, 50, "Agua Salada", "Azul", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(132, "Transformación", 4, 0.3, "Ditto", 0, 0, "Ciudad", "Morado", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(133, "Evolución", 6.5, 0.3, "Campo", 87.5, 12.5, "Ciudad", "Marrón", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(134, "Burbuja", 29, 1, "Campo", 87.5, 12.5, "Ciudad", "Azul", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(135, "Relámpago", 24.5, 0.8, "Campo", 87.5, 12.5, "Ciudad", "Amarillo", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(136, "Llama", 25, 0.9, "Campo", 87.5, 12.5, "Ciudad", "Rojo", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(137, "Virtual", 36.5, 0.8, "Mineral", 0, 0, "Ciudad", "Rosa", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(138, "Espiral", 7.5, 0.4, "Agua-1-Agua-3", 87.5, 12.5, "Agua Salada", "Azul", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(139, "Espiral", 35, 1, "Agua-1-Agua-3", 87.5, 12.5, "Agua Salada", "Azul", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(140, "Armazón", 11.5, 0.5, "Agua-1-Agua-3", 87.5, 12.5, "Agua Salada", "Marrón", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(141, "Armazón", 40.5, 1.3, "Agua-1-Agua-3", 87.5, 12.5, "Agua Salada", "Marrón", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(142, "Fósil", 59, 1.8, "Volador", 87.5, 12.5, "Montaña", "Morado", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(143, "Dormir", 460, 2.1, "Monstruo", 87.5, 12.5, "Montaña", "Negro", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(144, "Congelar", 55.4, 1.7, "Desconocido", 0, 0, "Raro", "Azul", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(145, "Eléctrico", 52.6, 1.7, "Desconocido", 0, 0, "Raro", "Amarillo", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(146, "Llama", 60, 2, "Desconocido", 0, 0, "Raro", "Rojo", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(147, "Dragón", 3.3, 1.8, "Agua-1-Dragón", 50, 50, "Agua Dulce", "Azul", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(148, "Dragón", 16.5, 4, "Agua-1-Dragón", 50, 50, "Agua Dulce", "Azul", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(149, "Dragón", 210, 2.2, "Agua-1-Dragón", 50, 50, "Agua Dulce", "Marrón", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(150, "Genético", 122, 2, "Desconocido", 0, 0, "Raro", "Morado", "Primera", "NULL", "NULL", "NULL");
INSERT INTO pokemon_detail(num_pokedex, category, weight, height, egg_group, male, female, habitat, colour, generation, figure, fingerprint, scream) values(151, "Nueva especie", 4, 0.4, "Desconocido", 0, 0, "Raro", "Rosa", "Primera", "NULL", "NULL", "NULL");

/*EvolutionForm*/
INSERT INTO evolution_form(name) values("Nivel");
INSERT INTO evolution_form(name) values("Piedra agua");
INSERT INTO evolution_form(name) values("Piedra fuego");
INSERT INTO evolution_form(name) values("Piedra hoja");
INSERT INTO evolution_form(name) values("Piedra lunar");
INSERT INTO evolution_form(name) values("Piedra trueno");
INSERT INTO evolution_form(name) values("Intercambio");

/*EvolutionFrom*/
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 2, 1);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 3, 2);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 5, 4);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 6, 5);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 8, 7);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 9, 8);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 11, 10);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 12, 11);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 14, 13);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 15, 14);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 17, 16);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 18, 17);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 20, 19);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 22, 21);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 24, 23);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(6, 26, 25);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 28, 27);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 30, 29);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(5, 31, 30);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 33, 32);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(5, 34, 33);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(5, 36, 35);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(3, 38, 37);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(5, 40, 39);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 42, 41);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 44, 43);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(4, 45, 44);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 47, 46);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 49, 48);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 51, 50);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 53, 52);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 55, 54);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 57, 56);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(3, 59, 58);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 61, 60);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(2, 62, 61);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 64, 63);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(7, 65, 64);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 67, 66);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(7, 68, 67);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 70, 69);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(4, 71, 70);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 73, 72);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 75, 74);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(7, 76, 75);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 78, 77);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 80, 79);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 82, 81);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 85, 84);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 87, 86);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 89, 88);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(2, 91, 90);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 93, 92);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(7, 94, 93);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 97, 96);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 99, 98);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 101, 100);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(4, 103, 102);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 105, 104);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 110, 109);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 112, 111);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 117, 116);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 119, 118);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(2, 121, 120);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 130, 129);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(2, 134, 133);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(6, 135, 133);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(3, 136, 133);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 139, 138);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 141, 140);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 148, 147);
INSERT INTO evolution_from(id_form, num_pokedex_evolutioned, num_pokedex_origin) values(1, 149, 148);

COMMIT;